### ISSUE TITLE
Add options to search FY folders

### ISSUE THREAD

**Issue by CherrelleTucker** [CherrelleTucker/snwg-automation#31]
### Milestone

FY24 M1 (Milestone Title)

### Description

Current script searches only one specified FY folder. Add options in custom menu botton to search each FY folder upon demand.

### Examples or References

- [Script - Container: actionTrackerSheet](https://script.google.com/u/0/home/projects/10JxC5rpwFaZ2b2Si2cPLqmeIquKmvUSz47HuaOLoOJUE_LuOYFSGa9MD/edit)
- [FY24 folder ID: 1SRIUs7CUEdGUw0r1PI52e0OJpfXYN0z8](https://drive.google.com/drive/folders/1SRIUs7CUEdGUw0r1PI52e0OJpfXYN0z8)
- [FY23 Folder ID: 1WKYw4jnP6ejRkOLAIPoPvbEYClaLE4eR](https://drive.google.com/drive/folders/1WKYw4jnP6ejRkOLAIPoPvbEYClaLE4eR)

### Deliverable

- [ ] Search FY 23 folder button
- [ ] Search FY 24 folder button
- [ ] Search All folders button?

### Implementation Blockers or Dependencies

Concerns: Adding a search All button could take a significant amount of time. Add a splash warning for this?

**Comment by CherrelleTucker** [comment]
Do I really want to do this? I don't think I care enough about it or that it will add significant functionality.
