### ISSUE TITLE
add All Open Actions Tab

### ISSUE THREAD

**Issue by CherrelleTucker** [CherrelleTucker/snwg-automation#34]
### Description

Add script functions that collect all open actions from other tabs and condenses them into one "All Actions" tab.

### Examples or References

[Container: Action Tracking Sheet](https://script.google.com/u/0/home/projects/10JxC5rpwFaZ2b2Si2cPLqmeIquKmvUSz47HuaOLoOJUE_LuOYFSGa9MD/edit)

### Deliverable

- [ ] ALL Open Actions tab in Action Items Sheet
- [ ] Open actions from MO tab are populated in ALL Open Actions
- [ ] Open actions from SEP tab are populated in ALL Open Actions

### Implementation Considerations

Additional tabs for DevSeed and Assessment will eventually be added. Endure documentation and modularization can easily and quickly support that future modification.
