### ISSUE TITLE
pull and push actions from SEP and DevSeed agendas

### ISSUE THREAD

**Issue by CherrelleTucker** [CherrelleTucker/snwg-automation#39]
### Description

pull actions from SEP and DevSeed agendas

### Deliverable

- [x] pull actions from SEP agendas
- [x] push actions from SEP agendas
- [x] pull actions from DevSeed agendas
- [x] push actions from DevSeed agendas

### Related Issues

#20
