### ISSUE TITLE
Clean up action items script

### ISSUE THREAD

**Issue by CherrelleTucker** [CherrelleTucker/snwg-automation#41]
### Description

make all the things work, please. 

### Deliverable

- [x] remove all open actions script functions to replace with in-sheet query for more responsive updates. 
- [x] Pull functions accommodate both .docx and Google doc files
- [x] Pull functions populate Source column with newly created Doc link if original file was .docx
- [x] Push functions recognize both [Who What Status] and [Status Owner Action] tables.
