### ISSUE TITLE
Completed Action Slackbot

### ISSUE THREAD

**Issue by CherrelleTucker** [CherrelleTucker/snwg-automation#54]
### Description

Users don't want to access a spreadsheet to find and update items. Develop a slackbot that quickly and easily updates actions in the spreadsheet for users so that they don't have to go to a different source.  

### Deliverable

- [x] /done command
- [x] bot accessible in comments
- [x] bot accessible in channels
- [x] updates all instances of the action item
- [x] reports action taken by user

### Implementation Considerations

Slackbots are only available in paid accounts. The majority of the actions are coded in Google Apps Script, then sent to Slack using an "Incoming webhook" URL. Each user will need their own copy of the Script and of the SlackBot. Previously attempted formatting shows that slack does not recognize italics, bold, underlined or hyperlinked text. Hyperlinks can be included and be active, but cannot be shortened [(Example)](https://www.examplehyperlink.com/)

### Related Issues

#53
